ALTER TABLE ITENS
ADD COLUMN criado_por BIGINT NOT NULL,
ADD CONSTRAINT FK_criado_por FOREIGN KEY (criado_por) REFERENCES USUARIOS(id);

ALTER TABLE ITENS
ADD COLUMN ultimo_registro BIGINT,
ADD CONSTRAINT FK_ultimo_registro FOREIGN KEY (ultimo_registro) REFERENCES REGISTROS(id);
